{ haskellPackages }:

with haskellPackages; [
  # Boolean
  # HTTP
  # HUnit
  # IfElse
  # MemoTrie
  # MissingH
  # QuickCheck
  # quickcheck-instances
  # abstract-deque
  # abstract-par
  # adjunctions
  # aeson
  # amqp
  # async
  # # attempt
  # attoparsec
  # attoparsec-conduit
  # # attoparsec-enumerator
  # base
  # base-unicode-symbols
  # base16-bytestring
  # base64-bytestring
  # basic-prelude
  # bifunctors
  # bindings-DSL
  # blaze-builder
  # blaze-builder-conduit
  # # blaze-builder-enumerator
  # blaze-html
  # blaze-markup
  # blaze-textual
  # bool-extras
  # byteable
  # byteorder
  # bytes
  # bytestring
  # bytestring-mmap
  # # bytestring-show
  # case-insensitive
  # cassava
  # categories
  # cereal
  # cereal-conduit
  # charset
  # checkers
  # chunked-data
  # classy-prelude
  # classy-prelude-conduit
  # cmdargs
  # comonad
  # comonad-transformers
  # composition
  # # compressed
  # cond
  # conduit
  # conduit-combinators
  # conduit-extra
  # configurator
  # connection
  # constraints
  # containers
  # contravariant
  # convertible
  # cpphs
  # criterion
  # cryptohash
  # css-text
  # curl
  # data-checked
  # data-default
  # data-default-class
  # data-fix
  # derive-storable
  # # diagrams
  # # diagrams-builder
  # # diagrams-core
  # # diagrams-svg
  # # diagrams-lib
  # # diagrams-graphviz
  # directory
  # distributive
  # dlist
  # dlist-instances
  # dns
  # doctest
  # doctest-prop
  # either
  # enclosed-exceptions
  # errors
  # exceptions
  # extensible-exceptions
  # failure
  # fast-logger
  # fgl
  # file-embed
  # filemanip
  # filepath
  # fingertree
  # fmlist
  # foldl
  # free
  # # free-functors
  # free-vl
  # freer-effects
  # fsnotify
  # fuzzcheck
  # # ghc-datasize
  # ghc-paths
  # graphviz
  # groups
  # hakyll
  # hamlet
  # hashable
  # hashtables
  # haskell-lexer
  # haskell-src
  # haskell-src-exts
  # here
  # hmatrix
  # hslogger
  # hspec
  # hspec-expectations
  # hspec-megaparsec
  # hspec-smallcheck
  # hspec-wai
  # html
  # http-client
  # http-client-tls
  # http-date
  # http-media
  # http-types
  # interpolate
  # io-memoize
  # io-storage
  # io-streams
  # json
  # json-stream
  # kan-extensions
  # kdt
  # keys
  # language-c
  # lattices
  # lens
  # lens-action
  # lens-aeson
  # lens-datetime
  # lens-family
  # lens-family-core
  # lifted-async
  # lifted-base
  # linear
  # list-extras
  # list-t
  # logging
  # logict
  # machinecell
  # machines
  # megaparsec
  # mime-mail
  # mime-types
  # mmorph
  # monad-control
  # monad-coroutine
  # monad-logger
  # monad-loops
  # monad-par
  # monad-par-extras
  # monad-stm
  # monadloc
  # mono-traversable
  # monoid-extras
  # mtl
  # multimap
  # network
  # network-simple
  # newtype
  # numbers
  # operational
  # optparse-applicative
  # pandoc
  # parallel
  # parallel-io
  # parsec
  # parsers
  # pipes
  # pipes-attoparsec
  # pipes-binary
  # pipes-bytestring
  # pipes-concurrency
  # pipes-extras
  # pipes-group
  # pipes-http
  # pipes-network
  # pipes-parse
  # pipes-safe
  # pipes-text
  # pipes-zlib
  # pointed
  # posix-paths
  # postgresql-simple
  # pretty-show
  # process
  # process-extras
  # profunctors
  # random
  # reducers
  # reflection
  # regex-applicative
  # regex-base
  # regex-compat
  # regex-posix
  # resourcet
  # retry
  # safe
  # sbv
  # scalpel
  # scientific
  # scotty
  # semigroupoids
  # semigroups
  # semiring-simple
  # servant
  # servant-blaze
  # servant-client
  # servant-docs
  # servant-foreign
  # servant-js
  # servant-server
  # shake
  # shakespeare
  # shelly
  # silently
  # simple-reflect
  # singletons
  # smallcheck
  # speculation
  # split
  # spoon
  # stm
  # stm-chans
  # stm-stats
  # streaming
  # streaming-bytestring
  # strict
  # stringsearch
  # strptime
  # syb
  # system-fileio
  # system-filepath
  # tagged
  # tar
  # tardis
  # tasty
  # tasty-hspec
  # tasty-hunit
  # tasty-quickcheck
  # tasty-smallcheck
  # temporary
  # text
  # text-format
  # text-show
  # these
  # thyme
  # time
  # time-recurrence
  # tls
  # total
  # transformers
  # transformers-base
  # trifecta
  # turtle
  # uniplate
  # units
  # unix-compat
  # unordered-containers
  # uuid
  # vector
  # vector-sized
  # void
  # wai
  # warp
  # weigh
  # x509
  # x509-store
  # x509-system
  # yaml
  # z3
  # zippers
  # zlib
]
