setopt extendedglob
unsetopt correct

bindkey "^[[1~" beginning-of-line
bindkey "^[[4~" end-of-line
bindkey '^[[H'  beginning-of-line                   # HOME
bindkey '^[[F'  end-of-line                         # END
bindkey '^?'    backward-delete-char                # BACKSPACE
bindkey '^[[3~' delete-char                         # DELETE
bindkey '^[[2~' overwrite-mode                      # INSERT
bindkey '^[[5~' history-beginning-search-backward   # PAGE UP
bindkey '^[[6~' history-beginning-search-forward    # PAGE DOWN
# bindkey '^R'    history-incremental-search-backward # SEARCH HISTORY
# bindkey '^R'    history-incremental-pattern-search-backward
# bindkey '^F'    history-incremental-pattern-search-forward

# Ensure that arrow keys work as they should
# bindkey '\e[A' up-line-or-history
# bindkey '\e[B' down-line-or-history

rgrep() { grep -iR $1 *; }
f() { find ./ | grep $1; }

# NixOS command-not-found support
if [ -x /run/current-system/sw/bin/command-not-found ]; then
    command_not_found_handler () {
        /run/current-system/sw/bin/command-not-found $@
    }
fi
